### ISSUE TITLE
Am I in an echo chamber? Y/N?

### ISSUE THREAD

**Issue by Brunty** [phpem/hack24-2017#1]
"Donald Trump" is the input text

So also look for: #donaldtrump

Is there an article / link in the tweet? If so, visit that tweet, find that text in the article and run sentiment analysis against it.

Only include X history for a user? Maybe last 7 days?

Find retweets / replies from the user, then we can work out if that friend from the RT / reply is also sharing the same sentiment

**Comment by cooperaj** [comment]
Took you a while.
